feat: 캐릭터 설정 화면
software-maestro-starting-blue/fourtoon-cookie-frontend pull request #11
Opened 2024-07-31 04:36 UTC by minseojo

### [feat] 캐릭터 설정 화면
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-
---
* 구현 내용
* 캐릭터 설정 화면 구현

* 추가 발생한 문제(논의 사항)

### 화면 예시
---

2024-07-31 05:19 UTC, JuneBridge03 requested changes
마지막 설정화면까지 왔군요..! 너무 수고하셨습니다~

다음과 같이 코멘트를 남겨드립니다..!

다만, 향후 프론트 통합 작업을 제가 하기로 결정하였으므로 코멘트에 대한 수정 반영은 제가 구현하여서 다시 코드리뷰 받겠습니다.

2024-07-31 05:19 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/member.ts
> +    throw new Error("getMember error");
throw를 catch 내부에서 하는 것도 괜찮아 보입니다..!
그리고 try문 내에서 만약에 status != 200 인 경우에 throw를 하는 것도 괜찮아 보입니다.

2024-07-31 05:19 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterList/CharacterList.tsx
> +import React from 'react';
기존에 캐릭터 선택 페이지 구현하면서 만들어졌던 컴포넌트를 활용하면 될 듯 하여서 이는 삭제한 후에 pull 받으면 될 듯 합니다.

2024-07-31 05:19 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
> +        const memberData = await getMember('2abae1cc-c4c3-4349-b8aa-38e4fefbd7fa');
UUID 공개.. 굉장히 위험한 듯 합니다.
로직 수정해야 할 듯 합니다.

2024-07-31 05:19 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/SettingPage/naruto.png
오...

2024-07-31 05:19 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
> +  );
컴포넌트 분리 필요해 보입니다.

2024-07-31 05:19 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
> +import { Member } from '../../types/member';
type import 추가해야 할 듯 합니다.

2024-07-31 05:19 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterList/CharacterList.tsx
> +import { Character } from '../../../types/character';
type import 추가해야 할 듯 합니다.

2024-07-31 05:19 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/member.ts
> +import { Member } from "../types/member";
type import 추가해야 할 듯 합니다.

2024-08-02 04:41 UTC, SproutMJ reviewed
확인하고 댓글 남겨주세요!

2024-08-02 04:41 UTC, SproutMJ commented on fourtoon-cookie/src/apis/member.ts
> +export const getMember = async (memberId: string): Promise<Member> => {
js에는 uuid라는 자료형이 없겠지요?

2024-08-02 04:41 UTC, SproutMJ commented on fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
> +                source={require('./naruto.png')}
png 파일은 다른 거로 변경되어야 하겠지요?

2024-08-02 04:41 UTC, SproutMJ commented on fourtoon-cookie/src/pages/SettingPage/naruto.png
킹작권 이슈로 빼는게 좋지 않을까 싶습니다...

2024-08-03 12:05 UTC, JuneBridge03 commented
일부 비슷한 로직을 TSK-245에서 구현 중이어서 해당 내용까지 pull 받은 이후에 정확하게 구현하고 code review 받겠습니다.

+ code review 답장(및 반영)도 그때쯤에 진행될 듯 합니다.

2024-08-04 12:33 UTC, JuneBridge03 commented on fourtoon-cookie/App.tsx
> +      <Stack.Navigator initialRouteName="SettingPage" screenOptions={{ headerShown: false }}>
추후 수정될 예정입니다~

2024-08-04 12:33 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/member.ts
> +    throw new Error("getMember error");
추후에 코드가 일관적으로 바뀌어서 고려 안 해도 괜찮을 듯 합니다

2024-08-04 12:33 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterList/CharacterList.tsx
> +import React from 'react';
그냥 그대로 두었습니다 일단,

2024-08-04 12:33 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
> +        const memberData = await getMember('2abae1cc-c4c3-4349-b8aa-38e4fefbd7fa');
수정하였습니다~!

2024-08-04 12:33 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
> +  );
분리 하였습니다~

2024-08-04 12:34 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
> +import { Member } from '../../types/member';
type import 추가했습니다~

2024-08-04 12:34 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterList/CharacterList.tsx
> +import { Character } from '../../../types/character';
추가하였습니다~

2024-08-04 12:34 UTC, SproutMJ approved these changes

2024-08-04 12:35 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/member.ts
> +import { Member } from "../types/member";
추후 수정될 예정입니다~

2024-08-04 12:35 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/SettingPage/SettingPage.tsx
> +                source={require('./naruto.png')}
네엡...

2024-08-04 12:36 UTC, minseojo commented
캐릭터 설정화면 코드리뷰 해주시고 직접 수정까지 해주시고 감사합니다!

2024-08-04 12:37 UTC, JuneBridge03 approved these changes

2024-08-04 12:37 UTC, merged