[feat] API 추상화 및 jwt 토큰 관리 로직 추가
software-maestro-starting-blue/fourtoon-cookie-frontend pull request #13
Opened 2024-08-02 06:31 UTC by JuneBridge03

### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-244
---
* 구현 내용
1. jwt 토큰 관리를 위해 refresh하는 로직을 추가하였습니다.
2. JwtToken을 검증하고 이를 통해 API를 전달할 수 있도록 api method를 추상화 하였습니다.
3. 이에 따라 여러 api method를 수정하고 이를 활용하는 부분도 적절하게 수정하였습니다.

* 추가 발생한 문제(논의 사항)
1. 에러 관련 로직을 추가해야 합니다. 이는 TSK-246에서 대대적으로 실행될 예정입니다.
2. 시작 및 회원가입 페이지 구현을 통해 Jwt 토큰 관리를 더욱 철저하게 하는 로직을 구성해야 합니다. 이는 TSK-245에서 실행될 예정입니다.

### 화면 예시
---
실 구현이 아닌 그저 로직 추가이므로 화면 예시는 첨부하지 않겠습니다.

2024-08-02 07:59 UTC, SproutMJ reviewed
확인 했습니다. 리뷰 남긴 부분만 확인해주세요!

2024-08-02 07:59 UTC, SproutMJ commented on fourtoon-cookie/src/apis/api.ts
> +import { JWTToken } from "../types/jwt";
여기에 type이 들어가야 하는지요...

2024-08-02 07:59 UTC, SproutMJ commented on fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateContext.tsx
> +import { JWTToken } from '../../../types/jwt';
여기도 type이 붙어야 할까요?

2024-08-02 07:59 UTC, SproutMJ commented on fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateProvider.tsx
> +            } catch (e) {
여기 console로 되어있는거같은데 예외가 무시될 것 같아요

2024-08-02 12:45 UTC, minseojo requested changes
확인했습니다! 무한루프 문제가 있어보여 이 부분만 체크 해주시면 감사하겠습니다.

2024-08-02 12:45 UTC, minseojo commented on fourtoon-cookie/src/apis/api.ts
> +            } else if (response.status === 401) {
계속해서 401을 반환하면 무한 루프에 빠지므로 해당 시뮬레이션에 대해 처리해야 할 것 같습니다.

2024-08-02 12:45 UTC, minseojo commented on fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateProvider.tsx
> +                await AsyncStorage.setItem('jwtToken', JSON.stringify(jwtToken));
'jwtToken' 단어를 AsyncStorage의 상수로 관리하는게 좋을 것 같습니다.

2024-08-03 06:27 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateProvider.tsx
> +                await AsyncStorage.setItem('jwtToken', JSON.stringify(jwtToken));
GlobalSelectionCharacter의 경우에도 아직 상수화가 안 된듯 합니다

따라서 일관성을 유지하기 위해서 코드를 저렇게 한 것이며 수정을 원하신다면 추후에 다른 브랜치에서 이를 해결하는 것이 좋을 듯 합니다.

2024-08-03 06:27 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/api.ts
> +import { JWTToken } from "../types/jwt";
24d4ff48f4b4b8b96e9df0adade138915e7a3e7b

해당 커밋에서 해결하였습니다.

2024-08-03 06:27 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateContext.tsx
> +import { JWTToken } from '../../../types/jwt';
24d4ff48f4b4b8b96e9df0adade138915e7a3e7b

해당 커밋에서 해결하였습니다.

2024-08-03 06:28 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/global/GlobalJwtToken/GlobalJwtTokenStateProvider.tsx
> +            } catch (e) {
3eaca91a2e821f39b988f69a3a4472091d090d60

해당 커밋에서 해결하였습니다.

+ 더불어서, 에러 핸들링과 같은 경우에는 PR 멘트에서 말씀드린 것과 같이 TSK-246에서 작업될 예정입니다.

2024-08-03 06:29 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/api.ts
> +            } else if (response.status === 401) {
c9722299e6b9685b68017aa5c4319f660f06657a

해당 커밋에서 해결하였습니다.

+ 현재는 boolean으로 하였지만, 추후 정책을 바꾸면서 해당 부분을 number(count)로 바꾸는 것이 좋을 듯 합니다.

2024-08-03 06:42 UTC, minseojo approved these changes
리뷰 반영 확인했습니다. 감사합니다~

2024-08-03 07:51 UTC, SproutMJ approved these changes

2024-08-03 07:51 UTC, merged