[feat] 그림 완성이 안된 경우의 기능 추가
software-maestro-starting-blue/fourtoon-cookie-frontend pull request #27
Opened 2024-09-05 08:52 UTC by minseojo

### [feat] 그림 완성이 안된 경우의 기능 추가
- [ ] bug (버그수정)
- [ ] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-284
---
* 구현 내용
그림 완성이 안된 경우의 기능 추가
Character.interface
selectionThumbnailUrl(이미지) 이용
name(유료캐릭터) 이용

* 추 후 의논할 내용
현재 정적이고 추상적인 메시지 `열심히 작업 중입니다. 조금만 기다려주세요!` 로 표현했지만,
해당 페이지에 Diary 의 `imageUrls` 뿐 만 아니라, `createdDateTime`을 넘겨주고 활용해 `~ 시간 소요 예정입니다.` 라는 느낌으로 변경해도 좋아보임

### 화면 예시
<img width="363" alt="스크린샷 2024-09-05 오후 5 46 25" src="https://github.com/user-attachments/assets/7a266573-69ce-42d1-8a44-62f79d91a4ad">

2024-09-05 09:18 UTC, SproutMJ approved these changes

2024-09-05 09:44 UTC, JuneBridge03 requested changes
코드 잘 보았습니다..!

다만, 일부 수정이 필요한 부분이 보여서 일단 수정요청을 보내드립니다..!

2024-09-05 09:44 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/DiaryPaintingImagesLayout/DiaryPaintingImagesLayout.tsx
> +    if (imageUrls.length === 0) {
백엔드의 작동 방식에 의하면 하나의 일기 내의 4장의 이미지를 모두 한 번에 생성하는 것이 아닌, 1장의 이미지를 독립적으로 생성합니다.
곧, 어떤 일기에 대해서는 imageUrl의 개수가 4 미만일 수도 있습니다.

따라서 imageUrls length < 4로 수정해야 할 것 같습니다.

2024-09-05 09:44 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryComponent/DiaryPaintingImagesLayout/DiaryPaintingImagesLayout.tsx
> +                )}
../../../../../assets/logo/logo-3.png 를 위에서 import 한 이후에,

source 부분에서 oneline if 문을 활용하는 편이 가독성 면에서 더 좋을 듯 합니다..!

2024-09-06 01:12 UTC, JuneBridge03 approved these changes
요청드린 부분 수정된 것 확인하였습니다..!

추후에 defaultCharacterImage 관련하여 논의해보면 좋을 듯 하네요

2024-09-06 01:13 UTC, merged