[feat] 백버튼 컴포넌트 구현
software-maestro-starting-blue/fourtoon-cookie-frontend pull request #3
Opened 2024-07-09 07:28 UTC by SproutMJ

# [feat] 백버튼 컴포넌트 구현
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-177
---
* 구현 내용
백버튼 컴포넌트 구현
버튼 위치는 스타일을 props에 전달해 외부에서 적용합니다.

* 추가 발생한 문제(논의 사항)

2024-07-10 14:32 UTC, JuneBridge03 requested changes
갑작스러운 Task에도 업무 수행해주셔서 너무 감사하다는 말씀을 드립니다.

다만, 다음과 같은 우려사항이 발생하여서 수정 요청을 드리는 바이니 참고해주시면 감사하겠습니다..!

2024-07-10 14:32 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
> +
컨벤션이나 여러 부분에서 굉장히 좋은 구성이라고는 생각합니다. 그러나, 다음과 같은 내용을 남겨드립니다.

1. onPress의 동작 과정을 구성하는 핸들러를 따로 구현하는 것이 좋다고 생각합니다. 
현재는 onPress={...} 이러한 방식으로 작성이 되어있는데, 이러한 형태보다는 
const handleOnPress = () => {
navigation.goBack();
}
과 같은 형태로 진행을 하여야 통일성과 추후에 로직을 점검 면에서 더 좋을 것 같습니다~
2. 인자로 onPress 핸들러도 받으면 좋기는 할 것 같습니다..!
다만, 핸들러가 무조건적으로 필수적인 인자는 아니고, 인자로 넣었을 때 반영해주는 정도로 코드 구현이 되면 좋을 것 같습니다.
예를 들어서

onPress?: () => void

와 같은 형태를 말씀드리는 것입니다.
특히 이러한 인자가 필요한 이후는 추후에 어떤 선택을 한 이후 뒤로가기 버튼을 눌렀을 때 이에 대한 정보를 넘겨주는 로직이 필요한데, 현 컴포넌트 구성이면 이러한 로직을 추가하기에 굉장히 어려운 구조입니다.

+ onPress?: () => void 보다는 onPress?: () => any 와 같은 느낌으로 작성하여서 onPress에서 any 타입의 state를 리턴해주거나, 제네릭으로 컴포넌트를 정의하거나, onPress가 undefined 일때만 기존 로직 (navigation.goBack())을 실행하거나 등의 선택지가 있는데, 어떤 방향으로 가야할 지는 고민해보면 좋을 것 같습니다..!

2024-07-10 14:32 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/BackButton/BackButtonStyles.ts
> +export default styles;
코드 컨벤션에 의하면 스타일 컴포넌트의 이름은 다음과 짓는 것이 더 좋을 것 같다는 생각입니다..!

BackButton.styled.ts

2024-07-10 14:32 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
> +import styles from './BackButtonStyles';
style을 import 하는 경우에는 컨벤션에 의하여

import * as S from './BackButton.styled';

와 같은 방식이 더 좋을 것 같습니다.

+ 그렇게 되면 밑의 코드에서도 단순 styles가 아닌 S.styles와 같이 수정해야 할 듯 합니다..!

2024-07-11 07:19 UTC, SproutMJ commented on fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
> +
1.은 적용 완료했습니다!
2. 스택 네비게이션을 사용하면 이전 화면의 상태가 유지되는 듯 하네요. 사실 백 버튼의 책임은 뒤로가기(navigation.goBack();)로 생각하고 있어서 핸들링 함수에 부가 기능(로직, 반환값 등)을 추가하는 것은 확장성에서 좋을 듯 하지만 타입을 정의할 수 없는 등의 문제가 생길 듯 합니다..

2024-07-11 07:20 UTC, SproutMJ commented on fourtoon-cookie/src/components/common/BackButton/BackButtonStyles.ts
> +export default styles;
컨벤션을 잊고있었네요 적용했습니다.

2024-07-12 16:08 UTC, JuneBridge03 approved these changes
수정사항 반영해주셔서 감사합니다~!

추가적인 의견이 존재하기는 하나, 해당 부분은 로직에 큰 문제가 있는 부분이 아니어서 일정 부분 반영해주신 후에 바로 PR 하시면 좋을 듯 합니다~

2024-07-12 16:08 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
> +
넵 저도 해당 문제점에 동의하며, 이는 앞으로 back button을 활용하면서 refactor 과정에서 조금 더 고민해보면 좋을 듯 합니다~!
현재 상황에서는 현 로직으로 충분하기에 좋은 것 같습니다!

2024-07-12 16:08 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
> +    }
두 가지의 궁금증과 요청이 있습니다..!

1. handleOnPress 함수가 const 로 구성이 되지 않고 function으로 구성되어 있는데, 이는 수정이 필요할 것 같습니다..!
2. 굳이 navigation.goBack()을 실현하는 로직을 리턴하기 보다는 함수 내에서 이를 바로 실현하는 것이 좋을 듯 합니다.

두 생각을 정리해서 코드로 구성하면 다음과 같을 듯 합니다.

const handlePress = () => {
  navigation.goBack();
}

+ 저번 리뷰를 보니, handleOnPress라는 굉장히 괴상한 함수명을 사용했군요.. 죄송합니다 ㅠㅠ
 handle 과 on 은 둘 중 하나만을 선택해야 하지 둘 다 선택하는 것은 좋지 않은 것 같아서... handlePress로 수정해주시면 너무 감사하겠습니다..

2024-07-12 16:08 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
> +import * as S from './BackButton.styled';
너무 좋은 듯 합니다 ㅎㅎ

2024-07-12 16:08 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
> +import {useNavigation} from "@react-navigation/native";
물론 현재는 굳이 싶기는 하지만, 나중에는 코드 통일성을 위해서 import를 어떻게 할까에 대해서도 논의해보면 좋을 듯 하네요~

예를 들어서
import { useNavigation } from "@react-navigation/native";에서

{useNavigation} vs { useNavigation } : 으로 띄어쓰기 차이가 있을 것 같고..
"@react-navigation/native" vs '@react-navigation/native' : 로 "로 통일한 것인지 혹은 '로 통일할 것인지 차이가 있을 것 같아요..!

아 물론 이건 지금 급한 이야기는 아닌 듯 합니다7

2024-07-13 05:46 UTC, minseojo approved these changes
좋은 코드 감사합니다~~

2024-07-13 05:46 UTC, merged

2024-07-13 05:52 UTC, SproutMJ commented on fourtoon-cookie/src/components/common/BackButton/BackButton.tsx
> +    }
아 넵 적용해서 새로 PR하겠습니다.