feat: 타임라인 페이지 구현
software-maestro-starting-blue/fourtoon-cookie-frontend pull request #5
Opened 2024-07-13 11:00 UTC by minseojo

# [pr타입] 제목
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-180
---
- common component 구현
1. Button 구현
2. Footer 구현
3. Header 구현
4. IconButton 구현
5. ImageButton 구현

- diary component 구현
1. Diaries 구현
2. Diary 구현
3. DiaryPaintingImages 구현

- page 구현
1. DiaryTimelinePage 구현

app.tsx 는 충돌여부를 고려해 커밋하지 않음
- app.tsx
```
import 'react-native-gesture-handler';
import React from 'react';
import { StyleSheet, View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import DiarySearchPage from './src/pages/DiarySearchPage/DiarySearchPage';
import DiaryTimelinePage from './src/pages/DiaryTimelinePage/DiaryTimelinePage';
import DiaryWritePage from './src/pages/DiaryWritePage/DiaryWritePage';
import SettingPage from './src/pages/SettingPage/SettingPage';

const Stack = createStackNavigator();

/*
npm install @react-navigation/native @react-navigation/stack
npm install react-native-screens react-native-safe-area-context

위 두개 다운로드.
*/
export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="DiaryTimelinePage"  screenOptions={{ headerShown: false }}>
        <Stack.Screen name="DiaryTimelinePage" component={DiaryTimelinePage} />
        <Stack.Screen name="DiarySearchPage" component={DiarySearchPage} />
        <Stack.Screen name="DiaryWritePage" component={DiaryWritePage} />
        <Stack.Screen name="SettingsPage" component={SettingPage} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

2024-07-14 15:51 UTC, JuneBridge03 requested changes
와... 양 대박이네요.. 진짜 수고 많으셨습니다

몇가지 놓치신 부분들이 있으셔서 이에 대한 리뷰를 남겨드렸습니다..!

한 번 확인해보시고 반영해주시면 더욱 좋을 것 같아요..!!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Diary/Diaries/Diaries.tsx
> +const Diaries = ({ diaries }: DiariesProps) => {
컨벤션상 props는 다음과 같이 받는 것이 좋을 듯 합니다.

const Diaries = (props: DiariesProps) => {
const { diaries } = props;
...(생략)...

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Diary/Diaries/Diaries.tsx
> +                    characterId={diary.characterId}
전개 연산자를 통해서 다음과 같이 코드를 줄일 수도 있을 듯 합니다.

<Diary
key={index}
{...diary}
/>

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Diary/Diary/Diary.tsx
> +    };
API 로직은 분리하는 것이 좋을 듯 합니다.

+ favorite에 대한 API가 POST로 되어있는 데, 이 상황에서 POST를 사용하신 이유가 궁금합니다..!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Diary/Diary/Diary.tsx
> +            </View>
이 부분은 여러 Layer와 여러 컴포넌트로 분리할 수 있다고 생각합니다.

물론 현재는 중요하지 않아보일 수는 있어도, 추후에 유지보수가 무조건 필요한 코드들이기에 유지보수가 용이한 형태로 수정하시면 너무 좋을 듯 합니다..!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Diary/DiaryPaintingImage/DiaryPaintingImages.tsx
> +const DiaryPaintingImages = ({ imageUrls }: DiaryPaintingImagesProps) => {
props는 전개 연산자로 받는 것이 컨벤션 상으로 좋을 듯 합니다..!

const DiaryPaintingImages = (props: DiaryPaintingImagesProps) => {
const { imageUrls } = props;

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/Header/Header.tsx
> +import FortuneCookieIcon from "../../../icon/fourtune_cookie.png"
import로 매직넘버화 할 수 있는 방법이 있다니 ㄷㄷ.. 좋네요

다만, icon에 대한 내용은 코드(src)이기 보다는 assets에 들어가는 것이 맞을 것 같기도 합니다 ㅠㅠ

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/Header/Header.tsx
> +            <Text style={S.styles.headerText}>포툰쿠키</Text>
추후에 상수화 관련 논의도 해보시죠!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/IconButton/IconButton.tsx
> +interface IconButtonProps {
interface, type과 같은 형태들은 모두 export하는 것이 좋을 듯 합니다..!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/ImageButton/ImageButton.tsx
> +interface ImageButtonProps {
interface, type과 같은 형태들은 모두 export하는 것이 좋을 듯 합니다..!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +}
이러한 친구들은 type에 넣는 것이 좋을 듯 합니다..!

(더 정확하게는 types/dto에 넣는 편이 좋아 보이고요)

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +    const addres = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEBIREBIQEhEPFRIVEBEWDxURFRAVFhMXGBcXFhMaJyggGBolHRcYLTEiJSktLy8uGR81RDMsNygtLisBCgoKDg0OGxAQGzIlHyYwMDAwMistLTAvLS8v
헉.... 상수화 필요해보이네요...!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +    };
API 호출과 같은 로직은 api 폴더 내에서 다른 파일에 구현하는 것이 더 좋다고 생각합니다..!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +            <FlatList
오... 이런 기능도 있군요 쌈@뽕하네요

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +    };
+ useEffect 내에서 활용되는 async function은 useEffect 내에서 로직을 구현하는 것이 코드 가독성과 유지 보수에서 좋을 듯 합니다..! 현재는 이의 순서가 오히려 뒤바뀌어서 이해하기 힘듭니다..!

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +}
+ 코드 상 보았을 때.. dto를 사용한다보다는 diary 객체를 사용한다는 느낌이 더 강한 듯 하네요

차라리 dto로 받는 로직을 api에서 구현한 이후, 현 파일에서는 해당 dto를 diary 객체로 바꾸어서 diaryData에 넣는 것이 더 좋아보입니다.

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +                renderItem={({ item }) => <Diaries diaries={[item]} />}
이렇게 하면 무한 스크롤이 되는 것인지 궁금합니다..!

현재 코드 상으로 보았을 때는 각 아이템들을 직접 렌더링 하는 것이 아닌 Diaries 객체에 여러 다이어리 내용들을 넣고, 해당 Diaries에서 Diary 컴포넌트를 활용하는 느낌이어서 헷갈리네요.

(정확하게는, diaryData가 여러 아이템으로 분해되어서 Diaries에 들어가는 형태라면 오히려 굳이 Diaries가 필요한가에 대한 의문이 들고, 아니라면 FlatList를 활용하는 이유에 대한 의문이 들기는 합니다..!)

2024-07-14 15:51 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/common/Footer/Footer.tsx
> +            <IconButton imageSource={SettingIcon} onPress={() => navigation.navigate('SettingsPage' as never)} />
이렇게 여러 반복을 단순 코드 상에서 하기 보다는 map함수를 활용하는 것이 더 이해하기 좋을 듯 합니다..!

const icons = [
  { source: TimelineIcon, pageName: 'DiaryTimelinePage' },
  { source: SearchIcon, pageName: 'DiarySearchPage' },
  { source: WriteIcon, pageName 'DiaryWritePage' },
  { source: SettingIcon, pageName: 'SettingsPage' },
];

return (
    <View style={S.styles.container}>
      {icons.map((icon, index) => (
        <IconButton
          key={index}
          imageSource={icon.source}
          onPress={() => navigation.navigate(icon.pageName as never)}
        />
      ))}
    </View>
  );

+ 사실 DiaryWritePage로 가는 경우 현 PR(#6) 상에서는 props가 필요하였는데, 이는 제가 수정하는 편이 더 좋을 듯 하네요. 번거롭기는 합니다.

2024-07-15 09:17 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Diary/Diary/Diary.tsx
> +    };
네네 저도 처음 보았을 때 PATCH라 생각하기는 해서 해당 방향으로 바꾸는 것이 좋을 듯 합니다..!
특히나 1번 경우에서 2번 경우로 바뀜에 따라서 더더욱 그런 것 같고요!

2024-07-15 09:18 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +                renderItem={({ item }) => <Diaries diaries={[item]} />}
오.. 디테일까지 너무 좋습니다

2024-07-17 13:05 UTC, SproutMJ requested changes
코드 잘 작성해주신거 잘 봤습니다!
언급한 부분만 확인해주시면 좋을 것 같습니다
감사합니다

2024-07-17 13:05 UTC, SproutMJ commented on fourtoon-cookie/src/apis/diaryApi.ts
> +        console.log("Error updating favorite status: ", error);
여기도 host 추출, log 봐주시면 좋을 것 같아요

2024-07-17 13:05 UTC, SproutMJ commented on fourtoon-cookie/src/components/common/IconButton/IconButton.tsx
> +    const { imageSource, onPress, style, imageStyle } = props;
...rest가 빠진 것 같습니다!

2024-07-18 05:42 UTC, minseojo commented on fourtoon-cookie/src/apis/diaryApi.ts
> +        const response = await fetch(`http://localhost:8080/diary/timeline/1?pageNumber=${pageNumber}`);
넵 감사합니다!

2024-07-18 05:43 UTC, minseojo commented on fourtoon-cookie/src/apis/diaryApi.ts
> +        return null;
아닙니다. 예외를 반환하도록 변경하겠습니다.

2024-07-18 05:43 UTC, minseojo commented on fourtoon-cookie/src/apis/diaryApi.ts
> +        const response = await fetch(`http://localhost:8080/diary/${diaryId}`, {
넵

2024-07-18 05:43 UTC, minseojo commented on fourtoon-cookie/src/apis/diaryApi.ts
> +        console.log("Error deleting diary: ", error);
넵 지우겠습니다

2024-07-18 05:43 UTC, minseojo commented on fourtoon-cookie/src/apis/diaryApi.ts
> +        console.log("Error updating favorite status: ", error);
넵

2024-07-18 05:43 UTC, minseojo commented on fourtoon-cookie/src/components/common/IconButton/IconButton.tsx
> +    const { imageSource, onPress, style, imageStyle } = props;
넵!

2024-07-18 18:35 UTC, SproutMJ approved these changes
확인 감사합니다!!

2024-07-18 18:35 UTC, minseojo commented on fourtoon-cookie/src/pages/DiaryTimelinePage/DiaryTimelinePage.tsx
> +    };
넵 !

2024-07-18 18:41 UTC, merged