[feat] DiaryWritePage 구현
software-maestro-starting-blue/fourtoon-cookie-frontend pull request #6
Opened 2024-07-14 14:08 UTC by JuneBridge03

# [feat] DiaryWritePage 구현
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-142
---
* 구현 내용
일기 작성 페이지 레이아웃을 전반적으로 개발하였습니다.

### TSK-144
---
* 구현 내용
날씨의 내용을 가지고 오는 로직을 구현했습니다.

### TSK-148
---
* 구현 내용
일기 작성시 자동으로 해시태그가 추가되는 로직을 구현했습니다.

### TSK-149
---
* 구현 내용
다음과 같은 Header의 로직을 구현하였습니다.
* 백버튼
* 날짜 선택
* 캐릭터 선택
* 작성 완료

### TSK-161
---
* 구현 내용
routing되어서 들어오는 props를 통해 "작성" 상태인지 "수정" 상태인지 확인 후 로직을 그에 맞추었습니다.

### TSK-152
---
* 구현 내용
결론적으로 모든 일기 작성 페이지가 다음과 같이 정합적으로 구현되었습니다.

* 헤더
* 작성 폼
* 해시 태그 목록
* api 통신 ([POST] /diary, [PATCH] /diary, [GET] /weather, [GET] /hashtag)
* gps 불러오기 로직 (expo-location)

* 추가 발생한 문제(논의 사항)
1. 서버와의 통신에서 인증 절차에 대한 로직을 추후에 추가할 필요성이 있습니다. (JWT)
2. 로컬에서의 캐릭터 아이디를 불러오는 방법이 필요합니다.
3. routing과 관련하여 다른 페이지와의 호환성을 추후에 지원해야 합니다.
4. hashtag 내용들을 관리하는 로직이 필요합니다.

2024-07-14 15:22 UTC, JuneBridge03 commented
아.. 잠시만요
isEdit = true; 일 경우에
 [GET] /diary 통해서 기존 내용을 넣어주는 로직도 추가해야 하겠네요

2024-07-14 15:53 UTC, JuneBridge03 commented
그리고 props 모두 undefined 여도 로직 구성 되도록 수정해보겠습니다77

2024-07-16 07:27 UTC, minseojo approved these changes

2024-07-16 07:27 UTC, minseojo commented on fourtoon-cookie/src/pages/DiaryWritePage/DiaryWritePage.tsx
> +    const handleDateChange = (newDate: Date) => {
메서드명을 handleDiaryDateChange()로 변경하는게 명확할 것 같습니다!

2024-07-16 07:27 UTC, minseojo commented on fourtoon-cookie/src/types/dto/diary.ts
> +    date: Date,
제가 createdAt으로 보내주다가 diaryDate를 보내줘서
diaryDate로 변경해주시면 감사하겠습니다!

2024-07-16 07:59 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryWritePage/DiaryWritePage.tsx
> +    const isWeatherUpdated = useRef<boolean>(false);
수정 반영 다음 커밋에서 진행하였습니다~ 감사합니다!

5251ba333eb6b00e1ba46c41d81048c17aed3e4d

2024-07-16 08:41 UTC, JuneBridge03 commented on fourtoon-cookie/src/types/diary.ts
> +    date: Date,
반영하였습니다~

02f7e7686466dcecfa14cbaef1b425e4773677f2

2024-07-16 08:41 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryWritePage/DiaryWritePage.tsx
> +    const handleDateChange = (newDate: Date) => {
반영하였습니다~

02f7e7686466dcecfa14cbaef1b425e4773677f2

2024-07-17 12:54 UTC, SproutMJ requested changes
코드 잘 구현해주셔서 간단하게 리뷰 남겨보았습니다!

2024-07-18 03:27 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/diary.ts
> +        const response = await fetch(`${API_URL}/diary/${diaryId}`, {
리뷰해주셔서 감사합니다.

해당 사안은 다음 커밋에서 수정하였습니다

42119600efb8ebbd3cb4c335f43ae342be9a6b5b

2024-07-18 03:27 UTC, JuneBridge03 commented on fourtoon-cookie/src/constants/api.ts
> +export const API_URL = "";
리뷰해주셔서 감사합니다.

해당 사안은 다음 커밋에서 수정하였습니다

42119600efb8ebbd3cb4c335f43ae342be9a6b5b

2024-07-18 03:28 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/hashtag.ts
> +    const queryString = new URLSearchParams(query).toString();
넵 보편적인 값이어서 queryString이라고 했던 것 같습니다.!

2024-07-18 03:28 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/diary.ts
> +                ' Authorization': `Bearer ${localStorage.getItem('accessToken')}` // TODO: accessToken 관리에 대한 논의가 필요합니다..!
네넵 아무래도 그렇게 하면 좋을 듯 합니다.!!

(물론, 해당 코드는 copilot이 짠 코드를 그대로 둔 것이지만...)

2024-07-18 03:31 UTC, JuneBridge03 commented on fourtoon-cookie/src/systemcall/gpt.ts
> +    console.log(gpsPos);
넵 로그 삭제는 다음 커밋에서 진행하였습니다!

9287e6adf8c32d950819a0ec6364617c76569299
831538796dd225cb9162c38d013d28e036800b56

2024-07-18 03:31 UTC, JuneBridge03 commented on fourtoon-cookie/src/systemcall/gpt.ts
> +        return null;
넵 로그 삭제는 다음 커밋에서 진행하였습니다!

9287e6adf8c32d950819a0ec6364617c76569299
831538796dd225cb9162c38d013d28e036800b56

2024-07-18 03:35 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/DiaryWritePage/DiaryWritePage.tsx
> +// 컴포넌트 인자 관리
넵 저도 TODO를 제외하는 나머지 주석은 굳이 싶어서 삭제를 다음 커밋에서 진행해보았습니다!

6aa3e21e6248094c71e66e5f96d5bee6af60f77d

2024-07-18 03:44 UTC, JuneBridge03 commented on fourtoon-cookie/src/systemcall/gpt.ts
> +        return null;
넵 null보다는 에러 throwing이 더 좋을 것 같아서 이를 반영한 커밋을 올렸습니다.

917727463cafce61fd2f3edd60aa7df6bf0ed37e

2024-07-18 17:53 UTC, SproutMJ approved these changes
확인 했습니다 감사합니다!

2024-07-18 17:54 UTC, merged