feat: 캐릭터 선택 화면 구현
software-maestro-starting-blue/fourtoon-cookie-frontend pull request #8
Opened 2024-07-26 06:13 UTC by minseojo

# [feat] 캐릭터 선택 화면 구현
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-223
---
* 구현 내용
- write 페이지에서 넘겨준 캐릭터 정보를 가지고 각 작품(artwork) 을 보여준다.
- 각 작품을 선택하면 해당하는 작품의 캐릭터를 보여준다.

- `Character` 타입 인터페이스 구현
- `CharacterSavedResponse` 응답 인터페이스 구현
- `getCharacters` API 구현
- `CharacterItem` 컴포넌트 구현
- `Header.tsx` 컴포넌트 구현
- `Tab.tsx` 컴포넌트 구현
- `CharacterSelectPage` 페이지 구현
- Character 관련 상수 추가

- `useMemo`모든 렌더링에서 그룹화된 문자를 다시 계산하지 않도록 함.    
    ```
    const groupedFreeCharacters = useMemo(() => groupByArtworkTitle(getCharactersByType(FREE, characters)), [characters]);
    const groupedPaidCharacters = useMemo(() => groupByArtworkTitle(getCharactersByType(PAID, characters)), [characters]);
    ```
    

#### 실행이미지
<img width="445" alt="스크린샷 2024-07-26 오후 3 09 32" src="https://github.com/user-attachments/assets/675dd637-1c32-45fc-bebc-9f4947683ad4">

2024-07-28 08:26 UTC, JuneBridge03 requested changes
매우 큰 로직이었는데, 구현해주셔서 감사합니다..!

다만, 다양한 코드를 작성하시다보니 놓치신 부분이 있으신 것 같아서 이에 대해 작성해두었습니다..!

2024-07-28 08:26 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx
> +          keyExtractor={(item) => item.id.toString()}
item보다는 다른 이름을 사용하는 것이 더 좋을 듯 합니다..! 현 코드를 보니 character가 더 좋을 듯 하네요

2024-07-28 08:26 UTC, JuneBridge03 commented on fourtoon-cookie/src/constants/character.ts
> +export type CharacterCategory = typeof FREE | typeof PAID;
이 친구는 상수화보다는 타입이 더 맞는 듯 합니다..!

2024-07-28 08:26 UTC, JuneBridge03 commented on fourtoon-cookie/src/apis/character.ts
> +            }));
return [ ...characterResponses ];와 같이 하셔도 동일하게 동작할 듯 합니다..!

2024-07-29 03:25 UTC, minseojo commented on fourtoon-cookie/src/constants/character.ts
> +export type CharacterCategory = typeof FREE | typeof PAID;
Character type으로 이동시켰씁니다

2024-07-29 03:36 UTC, minseojo commented on fourtoon-cookie/src/apis/character.ts
> +            }));
감사합니다!

2024-07-29 06:07 UTC, minseojo commented on fourtoon-cookie/src/components/global/GlobalSelectionCharacterStateContext.tsx
> +export const defaultValue: GlobalSelectionCharacterStateContextProps = {
좋습니다!

2024-07-29 06:08 UTC, minseojo commented on fourtoon-cookie/src/components/character/ArtworkList/ArtworkList.tsx
> +const ArtworkList = (props : ArtworkListProps) => {
ChacracterList, ChacterItem 컴포넌트 는 재사용 가능성이 있지만,
ArtworkList 는 CharacterSelectPage 에서만 보여줄 것 같아 말씀하신대로 패키지 이동했습니다~

2024-07-29 06:08 UTC, minseojo commented on fourtoon-cookie/src/components/character/CharacterList/CharacterList.tsx
> +        numColumns={3}
좋습니다~

2024-07-29 06:08 UTC, minseojo commented on fourtoon-cookie/src/components/global/GlobalSelectionCharacterStateContext.tsx
> +export default GlobalSelectionCharacterStateContext;
맞습니다!

2024-07-29 06:08 UTC, minseojo commented on fourtoon-cookie/src/constants/character.ts
> +export const PAID_CHARACTER_VISION_TYPES = ['STABLE_DIFFUSION'];
ENUM 변수로 변경했습니다!

2024-07-29 06:08 UTC, minseojo commented on fourtoon-cookie/src/constants/character.ts
> +export type CharacterCategory = typeof FREE | typeof PAID;
넵!

2024-07-29 06:08 UTC, minseojo commented on fourtoon-cookie/src/pages/CharacterSelectPage/Header/Hader.tsx
넵!

2024-07-29 07:08 UTC, SproutMJ reviewed
코드를 잘 짜주셔서 컨벤션 위주로 코드리뷰를 하게 된 것 같습니다. 확인만 해주시면 감사하겠습니다.

2024-07-29 07:08 UTC, SproutMJ commented on fourtoon-cookie/src/pages/CharacterSelectPage/Header/Header.tsx
> +import { CharacterPaymentType } from '../../../types/character';
여기도 type이 빠져있는 것 같아요

2024-07-29 07:08 UTC, SproutMJ commented on fourtoon-cookie/src/pages/CharacterSelectPage/Header/Tab/Tab.tsx
> +    const { isActive, label, onPress } = props;
...rest가 없습니다.

2024-07-29 08:44 UTC, minseojo commented
> 코드를 잘 짜주셔서 컨벤션 위주로 코드리뷰를 하게 된 것 같습니다. 확인만 해주시면 감사하겠습니다.

스타일 리뷰 반영했습니다!

2024-07-29 09:03 UTC, JuneBridge03 requested changes
너무 좋은 것 같습니다!

다만, FlatList와 관련하여 이슈가 조금 있는 듯 하네요 ㅠㅠ 한 번 확인해주시면 감사하겠습니다!

2024-07-29 09:03 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx
> +      );
이와 동시에 그 전 화면으로 라우팅 하는 로직이 필요할 듯 합니다..!

2024-07-29 09:42 UTC, minseojo commented on fourtoon-cookie/src/types/character.ts
> +};
서버의 응답값을 FREE, PAID를 이용해서 판별을하고 사용자에게 보여줄 때는 무료, 유료 값을 보여주는데 따로 관리하는게 좋을까요?

따로 PaymentType.enum 으로 관리하는게 좋을까요?

2024-07-29 09:44 UTC, minseojo commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx
> +      );
넵!

2024-07-29 10:21 UTC, JuneBridge03 commented on fourtoon-cookie/src/types/character.ts
> +};
네 서버에서 받는 값은 ENUM으로 하고, 화면에 표시하는 값은 constant로 관리하는 것이 더 좋을 듯 합니다~!

2024-07-29 10:43 UTC, minseojo commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx
> +          keyExtractor={(item) => item}
엇 그렇네요 반영했습니다~

2024-07-29 10:43 UTC, minseojo commented on fourtoon-cookie/src/types/character.ts
> +};
알겠습니다~!

2024-07-29 11:01 UTC, minseojo commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx
> +      );
```
    useEffect(() => {
        if (error) {
            navigation.goBack();
        }
    }, [error, navigation]);

```
에러가 발생하면 setError()로 상태를 변경하고 상태가 변경됨에 따라 그 전 화면으로 라우팅 하도록 했습니다

2024-07-29 11:46 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx
> +      );
useEffect와 error state를 활용하여서 페이지 전역의 에러를 한 번에 핸들링한다는 컨셉이 너무 좋은 듯 하네요..!

추후 validation, error handling 코드 작성할 때 조금 더 논의해보시죠!

2024-07-29 11:47 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/CharacterSelectPage.tsx
> +import { FREE_KOR, PAID_KOR } from '../../constants/character';
해당 import 활용 안 되는 것 같습니다..!

2024-07-29 11:53 UTC, JuneBridge03 commented on fourtoon-cookie/src/pages/CharacterSelectPage/ArtworkList/ArtworkList.tsx
> +  );
이렇게 render로 분리하기 보다는, 차라리 동일파일 하단에 다음과 같은 컴포넌트를 추가해도 좋을 듯 합니다..!

interface ArtworkItemProps {
    artworkName: string,
    artworkCharacters: Character[],
    selectedCharacter: Character,
    handleCharacterPress: (character: Character) => void,
}

const ArtworkItem = (props: ArtworkItemProps) => {
    const { artworkName, artworkCharacters, selectedCharacter, handleCharacterPress } = props;
    return (
        <View key={artworkName}>
           (...)
        </View>
    );
}

2024-07-30 10:13 UTC, SproutMJ approved these changes
확인했습니다!

2024-07-31 04:05 UTC, merged