[feat] 구글 회원가입/로그인 버튼 구현
software-maestro-starting-blue/fourtoon-cookie-frontend pull request #9
Opened 2024-07-27 09:16 UTC by SproutMJ

# [feat] 구글 회원가입/로그인 버튼 구현
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-162
---
* 구현 내용
* 구글 로그인을 진행하면 supabase에서 accesstoken을 발급받는 기능 구현

1. eas.json, .env.local 파일이 프로젝트 루트경로에 있어야 합니다.
2. 테스트 시 npm run eas:dev:android로 apk를 생성한 다음 시뮬레이터에 드래그-드랍으로 설치하고 npx expo start -c로 실행합니다.

* 추가 발생한 문제(논의 사항)
* 애플 버튼 만들어야 함
* 로그아웃 버튼 만들어야 함

2024-07-28 03:29 UTC, JuneBridge03 requested changes
와우..로그인 로직 잘 보았습니다
조금의 내용을 남겨드리니 확인 한 번 해주시면 감사하겠습니다!

2024-07-28 03:29 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Auth/GoogleAuthButton.tsx
> +            }}
onPress를 컴포넌트 로직 내가 아닌 외부 로직으로 이동하시는 것이 더 좋을 것 같습니다..!

2024-07-28 03:29 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Auth/GoogleAuthButton.tsx
> +                } catch (error: any) {
혹시 catch를 여러번 하지 않으시고 any로 두신 이유가 있으신지 궁금합니다..!

2024-07-28 03:29 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Auth/GoogleAuthButton.tsx
> +                    }
이 로직은 api로 가야 하나.. 라는 생각도 들기는 하네요

2024-07-28 03:29 UTC, JuneBridge03 commented on fourtoon-cookie/src/components/Auth/utils/supabase.ts
> +export const supabase = createClient(SUPABASE_API_URL, SUPABASE_API_KEY);
패키지를 컴포넌트 내보다는 다른 곳으로 이동하는 것이 더 좋아보입니다..!

2024-07-28 03:41 UTC, minseojo commented on fourtoon-cookie/src/components/Auth/GoogleAuthButton.tsx
> +                    }
통신 부분은 api 패키지로 빼고
구글 버튼을 호출하는 initialPage.tsx에서 onpress()={{googleApi}}를 이용하는건 어떤가요?

2024-07-28 13:26 UTC, SproutMJ commented on fourtoon-cookie/src/components/Auth/GoogleAuthButton.tsx
> +                } catch (error: any) {
기본 코드의 형태이긴 한데요 any로 모든 예외를 받은 다음 status 코드로 처리하는 것으로 보입니다.

2024-07-28 13:26 UTC, SproutMJ commented on fourtoon-cookie/src/components/Auth/GoogleAuthButton.tsx
> +            }}
handleOnPress로 함수 추출 했습니다

2024-07-28 13:27 UTC, SproutMJ commented on fourtoon-cookie/src/components/Auth/GoogleAuthButton.tsx
> +                    }
api를 호출을 직접적으로 하는 것이 아닌 라이브러리를 통해서 호출하는건데 어떻게 생각하시나요?

2024-07-28 13:30 UTC, SproutMJ commented on fourtoon-cookie/src/components/Auth/utils/supabase.ts
> +export const supabase = createClient(SUPABASE_API_URL, SUPABASE_API_KEY);
util 패키지를 만들어 이동했습니다.

2024-07-28 13:31 UTC, SproutMJ commented on fourtoon-cookie/src/components/Auth/GoogleAuthButton.tsx
> +                    }
준교님과 비슷한 의견이었는데요 이부분이 axios나 fetch같은 것으로 api를 호출하기보다  라이브러리로 하다보니 api로 분리하는 것에 대해 약간의 이질감은 있는 것 같습니다. 한번 논의해보는 것이 좋아보입니다.

2024-07-29 05:36 UTC, JuneBridge03 approved these changes

2024-07-29 05:36 UTC, minseojo approved these changes

2024-07-29 05:36 UTC, merged